#!/usr/bin/env python3
"""
Generate a model-to-cloud-config compatibility dictionary.

This script fetches the Meraki documentation page on Cloud Management with IOS-XE,
extracts the supported models table, and builds a dictionary mapping each model to
the minimum required Cloud Config version. The output is formatted as a Python
dictionary for easy inclusion in the Merakicat codebase.

Usage: python gen_ios_compat_dict.py > mc_min_ios_version.py
"""

from __future__ import annotations

import re
from typing import Dict, List

import requests
from lxml import html

SOURCE_URL = "https://documentation.meraki.com/Switching/Cloud_Management_with_IOS_XE"
VERSION_PATTERN = re.compile(r"\(([\d.]+)\+?\)")


def fetch_page_html(url: str) -> str:
    """Fetch the target page HTML."""
    response = requests.get(url, timeout=30)
    response.raise_for_status()
    return response.text


def extract_table_rows(page_html: str) -> List[List[str]]:
    """Extract rows from the supported models table."""
    document = html.fromstring(page_html)
    table_candidates = document.xpath("//table")
    for table in table_candidates:
        first_row_cells = table.xpath(".//tr[1]/*")
        headers = [
            " ".join(" ".join(cell.xpath(".//text()")).split())
            for cell in first_row_cells
        ]
        if headers[:4] == [
            "Product Family",
            "Models",
            "Cloud Config",
            "Device Config",
        ]:
            rows: List[List[str]] = []
            for row in table.xpath(".//tr[position()>1]"):
                cells = row.xpath("./td")
                if not cells:
                    continue
                rows.append(
                    [
                        " ".join(cell.xpath(".//text()")).strip()
                        for cell in cells
                    ]
                )
            return rows
    raise ValueError("Could not locate supported models table in page HTML.")


def normalize_cloud_config_value(raw_value: str) -> str | None:
    """Extract only the numeric cloud config version from a table cell."""
    match = VERSION_PATTERN.search(raw_value)
    if not match:
        return None
    return match.group(1)


def parse_models_cell(models_cell: str) -> List[str]:
    """Split model cell content into individual model names."""
    cleaned = " ".join(models_cell.replace("**", "").split())
    cleaned = re.sub(r"(?<=\d)\s+(?=[A-Z]{1,3}-)", "", cleaned)
    if not cleaned:
        return []
    return re.findall(r"[A-Z0-9]+(?:-[A-Z0-9]+)+", cleaned)


def build_model_compat_dict(page_html: str) -> Dict[str, str]:
    """Build a dictionary keyed by model with cloud config version values."""
    table_rows = extract_table_rows(page_html)
    compat_dict: Dict[str, str] = {}

    for columns in table_rows:
        if len(columns) < 3:
            continue

        models = parse_models_cell(columns[1])
        cloud_config_version = normalize_cloud_config_value(columns[2])
        if not models or cloud_config_version is None:
            # Some source rows are shifted one column left in the raw HTML export.
            # In those cases, model values are in column 0 and cloud version in 1.
            models = parse_models_cell(columns[0])
            cloud_config_version = normalize_cloud_config_value(columns[1])
        if not models or cloud_config_version is None:
            continue

        for model in models:
            compat_dict[model] = cloud_config_version

    return compat_dict


def main() -> None:
    """Fetch, parse, and print the compatibility dictionary."""
    page_html = fetch_page_html(SOURCE_URL)
    compat_dict = dict(sorted(build_model_compat_dict(page_html).items()))
    print("# This dictionary contains the minimum required software version for each model")
    print("# Generated by gen_ios_compat_dict.py\n")
    print("mc_min_ios_version = {")
    for model, version in compat_dict.items():
        print(f"    {model!r}: {version!r},")
    print("}")


if __name__ == "__main__":
    main()
